pipeline:
  name: cf-app-autoscaler-platform-pipeline
  git:
    owner: starkandwayne
    repo:  demo-autoscaler-deployments
    private_key: (( vault "concourse/demo/autoscaler/github:private_key" ))

  slack:
    channel: '#concourse'
    webhook: (( vault "concourse/demo/autoscaler/slack:webhook" ))

  vault:
    url:    https://10.4.1.7
    verify: no


  boshes:
    dev:
      url:      https://10.4.16.4:25555
      ca_cert:  (( vault "secret/dev/bosh/ssl/ca:certificate" ))
      username: admin
      password: (( vault "secret/dev/bosh/users/admin:password" ))

    uswest2demo:
      url:      https://10.4.1.4:25555
      ca_cert:  (( vault "secret/uswest2demo/bosh/ssl/ca:certificate" ))
      username: admin
      password: (( vault "secret/uswest2demo/bosh/users/admin:password" ))


  layouts:
    # genesis repipe                 ; if target is 'default'
    # genesis repipe -t azure        ; if target is 'azure' instead
    default: |+
      auto *dev
      dev -> uswest2demo

# adds testflight to the cf-app-autoscaler-platform-pipeline
groups:
- name: cf-app-autoscaler-platform-pipeline
  jobs:
  - ((append))
  - testflight

# adds the ci directtory to the resources available for dev-changes
resources:
- name: dev-changes
  source:
    paths:
    - ((append))
    - ci

# creates the testflight job. Comments point out information that needs updating when names change
jobs:
- name: testflight
  plan:
  - do:
    - in_parallel:
        steps:
        - get: dev-changes                                                    # is composed by the bosh director name + -changes i.e. dev + -changes
          trigger: true
          passed:
          - dev-cf-app-autoscaler                                             # is composed by the bosh director name + kit_shortname i.e. dev + -cf-app-autoscaler
          trigger: true
    - task: test-addons
      file: dev-changes/ci/tasks/test-addons.yml
      vars:
        BOSH_DIRECTOR:  dev                                                               # sets the bosh director's name
        CF_API:         (( vault "secret/exodus/dev/cf:api_domain" ))                     # Cf information path rely on the path
        CF_USERNAME:    (( vault "secret/exodus/dev/cf:admin_username" ))                 # created by the bosh director storing
        CF_PASSWORD:    (( vault "secret/exodus/dev/cf:admin_password" ))                 # the cf credentials
        GIT_DIRECTORY:  dev-changes                                                       # matches the `- get` step name above
        KIT_SHORTNAME:  cf-app-autoscaler
        VAULT_ADDR:     https://10.4.1.7                                                  # the vault addess holding secrets
        VAULT_ROLE:     (( vault "secret/exodus/ci/genesis-pipelines:approle-id" ))       # concourse approles's default path is used
        VAULT_SECRET:   (( vault "secret/exodus/ci/genesis-pipelines:approle-secret" ))   # may need updating if another is used

#- name: notify-uswest2demo-cf-app-autoscaler-changes
#  plan:
#    - (( inline ))
#    - in_parallel:
#        steps:
#          - (( merge on get ))
#          - get: uswest2demo-cache
#            passed:
#              - (( append ))
#              - testflight
