pipeline:
  name: cf-app-autoscaler-platform-pipeline
  git:
    owner: starkandwayne
    repo:  demo-autoscaler-deployments
    private_key: (( vault "concourse/demo/autoscaler/github:private_key" ))

#  notifications: parallel

  slack:
    channel: '#concourse'
    webhook: (( vault "concourse/demo/autoscaler/slack:webhook" ))

#  email:
#    stanza: here

  vault:
    url:    https://10.4.1.7
    verify: no

#  locker:
    

  boshes:
    dev:
      url:      https://10.4.16.4:25555
      ca_cert:  (( vault "secret/dev/bosh/ssl/ca:certificate" ))
      username: admin
      password: (( vault "secret/dev/bosh/users/admin:password" ))

    uswest2demo:
      url:      https://10.4.1.4:25555
      ca_cert:  (( vault "secret/uswest2demo/bosh/ssl/ca:certificate" ))
      username: admin
      password: (( vault "secret/uswest2demo/bosh/users/admin:password" ))

#  smoke-tests: run-my-smoke-tests
#  tagged: yes

  layouts:
    # genesis repipe                 ; if target is 'default'
    # genesis repipe -t azure        ; if target is 'azure' instead
    default: |+
      auto *dev
      dev -> uswest2demo


#jobs:
#- name: dev-cf-app-autoscaler
#  plan:
#  - do:
#    - task: bosh-deploy
#      config:
#        run:
#        - ((append))
#        -  path: ci/scripts/testflight.sh

groups:
- name: cf-app-autoscaler-platform-pipeline
  jobs:
  - ((append))
  - testflight

resources:
- name: dev-changes
  source:
    paths:
    - ((append))
    - ci


jobs:
- name: testflight
  plan:
  - do:
    - in_parallel:
        steps:
        - get: dev-changes
          trigger: true
          passed:
          - dev-cf-app-autoscaler
          trigger: true
    - task: test-addons
      file: dev-changes/ci/tasks/test-addons.yml
      vars:
        VAULT_ADDR: https://10.4.1.7
        VAULT_ROLE: (( vault "secret/exodus/ci/genesis-pipelines:approle-id" ))
        VAULT_SECRET: (( vault "secret/exodus/ci/genesis-pipelines:approle-secret" ))
        VAULT_SKIP_VERIFY: "true"