pipeline:
  name: cf-app-autoscaler-platform-pipeline
  git:
    owner: starkandwayne
    repo:  demo-autoscaler-deployments
    private_key: (( vault "concourse/demo/autoscaler/github:private_key" ))

#  notifications: parallel

  slack:
    channel: '#concourse'
    webhook: (( vault "concourse/demo/autoscaler/slack:webhook" ))

#  email:
#    stanza: here

  vault:
    url:    https://10.4.1.7
    verify: no

#  locker:
    

  boshes:
    dev:
      url:      https://10.4.16.4:25555
      ca_cert:  (( vault "secret/dev/bosh/ssl/ca:certificate" ))
      username: admin
      password: (( vault "secret/dev/bosh/users/admin:password" ))

    uswest2demo:
      url:      https://10.4.1.4:25555
      ca_cert:  (( vault "secret/uswest2demo/bosh/ssl/ca:certificate" ))
      username: admin
      password: (( vault "secret/uswest2demo/bosh/users/admin:password" ))

#  smoke-tests: run-my-smoke-tests
#  tagged: yes

  layouts:
    # genesis repipe                 ; if target is 'default'
    # genesis repipe -t azure        ; if target is 'azure' instead
    default: |+
      auto *dev
      dev -> uswest2demo


#jobs:
#- name: dev-cf-app-autoscaler
#  plan:
#  - do:
#    - task: bosh-deploy
#      config:
#        run:
#        - ((append))
#        -  path: ci/scripts/testflight.sh

groups:
- name: cf-app-autoscaler-platform-pipeline
  jobs:
  - ((append))
  - testflight

jobs:
- name: testflight
  plan:
  - do:
    - in_parallel:
        steps:
        - get: uswest2demo-changes
          trigger: true
        - get: uswest2demo-cache
          passed:
          - dev-cf-app-autoscaler
          trigger: true
    - task: test-add-ons
      config:
        platform: linux
        image_resource:
          name: ""
          source:
            repository: starkandwayne/concourse
            tag: latest
          type: registry-image
        inputs:
        - name: uswest2demo-changes
        - name: uswest2demo-cache
        run:
          path: ci/scripts/testflight.sh