platform: linux
image_resource:
  name: ""
  source:
    repository: starkandwayne/concourse
    tag: latest
  type: registry-image

inputs:
- name: dev-changes

run:
  path: dev-changes/ci/scripts/testflight.sh