platform: linux
image_resource:
  name: ""
  source:
    repository: starkandwayne/concourse
    tag: latest
  type: registry-image

inputs:
- name: ((GIT_DIRECTORY))

params:
  VAULT_ADDR:     ((VAULT_ADDR))
  VAULT_ROLE:     ((VAULT_ROLE))
  VAULT_SECRET:   ((VAULT_SECRET))
  GIT_DIRECTORY:  ((GIT_DIRECTORY))
  BOSH_DIRECTOR:  ((BOSH_DIRECTOR))

run:
  path: ((GIT_DIRECTORY))/ci/scripts/testflight.sh